%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Projection of Landsat 15 m or 30 m data to Sentinel-2 20 m resolution using bilinear and cubic convolution resampling %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear all; close all; clc
% Plesae read 'Read.me.txt' before implement this code
% The image 'PXS_15m_B1_B7_Brovey_odd.tif' was generated by implementing 'ProPADS30to15.m' 

[I0, R] = geotiffread('PXS_15m_B1_B7_Brovey_odd.tif'); 

info = geotiffinfo('20m_B4.tif'); % Sentinel-2 20 m reference band, just its 'info' and 'R' were used here.
[temp, R] = geotiffread('20m_B4.tif');

b1 = I0(:,:,1);
b2 = I0(:,:,2);
b3 = I0(:,:,3);
b4 = I0(:,:,4);
b5 = I0(:,:,5);
b6 = I0(:,:,6);
b7 = I0(:,:,7);
%% Input scale factor
K = 15/20; % projection of Landsat 15 m data to Sentinel-2 20 m resolution
% K = 30/20; % projection of Landsat 30 m data to Sentinel-2 20 m resolution
%% cubic convolution (cc) or bilinear (bl) resampling
resampler = 'cc'; % or resampling_type = 'bl';

b1 = bl_cc_resampling_at(b1,K,resampler);
b2 = bl_cc_resampling_at(b2,K,resampler);
b3 = bl_cc_resampling_at(b3,K,resampler);
b4 = bl_cc_resampling_at(b4,K,resampler);
b5 = bl_cc_resampling_at(b5,K,resampler);
b6 = bl_cc_resampling_at(b6,K,resampler);
b7 = bl_cc_resampling_at(b7,K,resampler);

%% Output
Output(:,:,1) = b1;
Output(:,:,2) = b2;
Output(:,:,3) = b3;
Output(:,:,4) = b4;
Output(:,:,5) = b5;
Output(:,:,6) = b6;
Output(:,:,7) = b7;
[row, col, band] = size(b5)
R.RasterSize = [row col];
% geotiffwrite('registered_20m.tif',int16(Output),R,'GeoKeyDirectoryTag',info.GeoTIFFTags.GeoKeyDirectoryTag);
geotiffwrite('registered_20m.tif',int16(Output),R,'GeoKeyDirectoryTag',info.GeoTIFFTags.GeoKeyDirectoryTag);

% Output = uint8(Output(:,:,[7,5,4]));
% figure, imshow(Output(:,:,[7,5,4]));



